name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::227163777560:role/github-actions-rflemig-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "rflemig-sa-east-1-terraform"
      aws-lock-dynamodb-table: "rflemig-sa-east-1-rflemig-terraform-lock"
